
export const SEND_USERNAME_PASSWORD = 'SEND_USERNAME_PASSWORD'
export const LOG_USER_OUT = 'LOG_USER_OUT'
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'

export const UPDATE_CONSENSUS = 'UPDATE_CONSENSUS'
export const UPDATE_SHOW_QUORUM_SUBMENU = 'UPDATE_SHOW_QUORUM_SUBMENU'
