
export const SEND_USERNAME_PASSWORD = 'SEND_USERNAME_PASSWORD'
export const LOG_USER_OUT = 'LOG_USER_OUT'
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'

export const UPDATE_BLOCKCHAIN = 'UPDATE_BLOCKCHAIN'
export const UPDATE_BOB_BALANCE = 'UPDATE_BOB_BALANCE'
export const UPDATE_ALICE_BALANCE = 'UPDATE_ALICE_BALANCE'
